<div class="box">
	<img src="<?php echo $this->getSkinUrl('images/marktfeed/logo-marktfeed.png'); ?>" style="float:left;margin: 18px 30px 0 10px;"/>
	<p>Marktfeed is de meest complete tool voor webshophouders die producten volledig automatisch op Marktplaats.nl willen plaatsen.<br/>
	Importeer eenvoudig je producten en zet deze automatisch om in kwalitatief goede Admarkt advertenties.</p>

	<p>Voor documentatie en ondersteuning zie <a href="https://www.marktfeed.nl" target="_blank">Marktfeed.nl</a></p>
    <div style="clear:both;width:1px;height:1px;font-size:1px;overflow:hidden;">&nbsp;</div>
</div>